spring:
  profiles:
    active: local
    include: google
app:
  jwt:
    jwt-secret-key: wafflestudio
    jwt-expiration-in-ms: 10800000
---

spring:
  config:
    activate:
      on-profile: local
    additional-location: classpath:application-dbInfo.yml
  datasource:
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=UTC
    username: waffle-team3
    password: Wafflestudio!
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      # create: 시작 시 테이블 drop 후 재생성
      # update: 시작 시 자동 migrate
      # none: db 그대로
      # create-drop: 시작 시 테이블 create, 종료 시 drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: google.client.id
            clientSecret: google.client.secret
            scope: profile
            response_type: code
          facebook:
            clientId: facebook.client.id
            facebookSecret: facebook.client.secret
            scope: profile


---

spring:
  config:
    activate:
      on-profile: dev
    additional-location: classpath:application-dbInfo.yml
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}