spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=UTC
    username: username
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      # create: 시작 시 테이블 drop 후 재생성
      # update: 시작 시 자동 migrate
      # none: db 그대로
      # create-drop: 시작 시 테이블 create, 종료 시 drop
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: dev
  profiles:
    include:
      - dbInfo
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create